---
- name: Installing
  hosts: all
  gather_facts: true
  become: true
  vars:
    mysql_root_pass: "mailbundle"
    packages:
      - python3-mysqldb
      - mysql-server

  tasks:
    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'

    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: install mysql server
      apt:
        pkg: "{{ packages }}"
        state: present

        #    - name: sql query
        # command:  mysql -u root --execute="ALTER USER 'root'@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY '"{{ mysql_root_pass }}"';"
    - name: create tables
      mysql_db:
        name: afterlogic
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        state: present

    - name: Enable service mysql
      service:
        name: mysql
        enabled: yes


