---
- name: Install php-fpm
  hosts: all
  gather_facts: true
  become: true
  vars:
    packages:
      - php7.4-cli
      - php7.4-curl
      - php7.4-common
      - php7.4-fpm
      - php7.4-gd
      - php7.4-json
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-opcache
      - php7.4-readline
      - php7.4-xml

  tasks:
    - name: install php-fpm
      apt:
        pkg: "{{ packages }}"
        state: present
    - name: backup default php configuration
      shell: /bin/cp -r  /etc/php/7.4 /etc/php/7.4_distr

    - name: "create directory"
      file:
        path: /opt/afterlogic/run/php-fpm
        state: directory
        mode: '0775'
        owner: afterlogic
        group: afterlogic
    
    - name: "create directory"
      file:
        path: /var/log/php-fpm
        state: directory
        mode: '0775'
        owner: afterlogic
        group: afterlogic

    - name: "create directory"
      file:
        path:  /opt/afterlogic/var/run/php-fpm/
        state: directory
        mode: '0775'
        owner: afterlogic
        group: afterlogic

    - name: copy php.ini
      template:
        src: templates/php.ini.j2
        dest: /etc/php/7.4/fpm/php.ini

    - name: copy php-fpm.conf
      template:
        src: templates/php-fpm.conf.j2
        dest: /etc/php/7.4/fpm/php-fpm.conf

    - name: copy www.conf
      # template:
      # src: "templates/www.conf.j2"
      # dest: "/etc/php/7.4/fpm/pool.d/www.conf"
      shell:  /bin/cp templates/www.conf.j2 /etc/php/7.4/fpm/pool.d/www.conf

    - name: Restart php7.4-fpm
      service:
         name: php7.4-fpm
         state: restarted

    - name: Restart nginx
      service:
         name: nginx
         state: restarted         

    - name: Update DB
      command: sudo -u afterlogic /bin/php -f templates/scripts/dbupdate.php

    - name: Data owner
      shell: /bin/chown afterlogic:afterlogic -R /opt/afterlogic/html/data/

    - name: Enable service php7.4-fpm
      service:
        name: php7.4-fpm
        enabled: yes

    - name: Enable cron
      shell: (crontab -l 2>/dev/null; cat templates/scripts/cron-root)| crontab -

  handlers:
    - name: restart php7.4-fpm
      service:
        name: php7.4-fpm
        state: restarted
